covercall/urls.py
from django.urls import path, include
from . import views
app_name = 'appcovercall'
urlpatterns = [
    path('home/<str:symbol>', views.index, name='home'),
    path('saveCoverCall/', views.save_covercall, name='saveCoverCall'),
    path('showSymbol/', views.show_symbol, name='showSymbol'),
    path('backtestting/', views.backtest, name='backtestting'),
    path('backtestdemo/', views.estimate, name='backtestdemo')
]

coverwarranty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('covercall/', include('covercall.urls')),
    path('covercall_backtest/', include('covercallbacktest.urls')),
    path('fpt2003backtest/', include('fpt2003backtest.urls')),
]

covercall/models.py
from django.db import models
from django.db.models import Model
# Create your models here.
class CoverCallStrate(models.Model):
    assetPrice = models.FloatField(null=True)
    strikePrice = models.FloatField(null=True)
    maturity = models.FloatField(null=True)
    rate = models.FloatField(null=True)
    startDate = models.DateField()
    endDate = models.DateField()
    symbol = models.CharField(max_length=10)
class ClosePrice(models.Model):
    date = models.DateField()
    symbol = models.CharField(max_length=10)
    closePrice = models.FloatField(null=True)

class CWPrice(models.Model):
    dateCW = models.DateField()
    symbolCW = models.CharField(max_length=10)
    openPriceCW = models.FloatField(null=True)
    highPriceCW = models.FloatField(null=True)
    lowPriceCW = models.FloatField(null=True)
    closePriceCW = models.FloatField(null=True)
    volumeCW = models.FloatField(null=True)
    valueCW = models.FloatField(null=True)

class CoverCallBacktest(models.Model):
    startdateBt = models.DateField()
    enddateBt = models.DateField()
    timerange = models.FloatField(null=True)
    c = models.FloatField(null=True)
    m = models.FloatField(null=True)
    n = models.FloatField(null=True)

class BackTestCover(models.Model):
    enddateBt = models.DateField()
    timerange = models.FloatField(null=True)
    rate = models.FloatField(null=True)
    strikePrice = models.FloatField(null=True)
    symbol = models.CharField(max_length=10)
    maturity = models.FloatField(default=0.5)

class BackTester(models.Model):
    enddateBt = models.DateField()
    timerange = models.FloatField(null=True)
    m = models.FloatField(null=True)
    n = models.FloatField(null=True)
    symbol = models.CharField(max_length=10)

covercall/forms.py
from django import forms

class Covercallstrate(forms.Form):
    assetPrice = forms.FloatField()
    strikePrice = forms.FloatField()
    maturity = forms.FloatField()
    rate = forms.FloatField()
    startDate = forms.DateField()
    endDate = forms.DateField()
    symbol = forms.CharField()

class Closeprice(forms.Form):
    date = forms.DateField()
    symbol = forms.CharField()
    closePrice = forms.FloatField()

class Cwprice(forms.Form):
    date = forms.DateField()
    symbol = forms.CharField()
    openPriceCW = forms.FloatField()
    highPriceCW = forms.FloatField()
    lowPriceCW = forms.FloatField()
    closePriceCW = forms.FloatField()
    volumeCW = forms.FloatField()
    valueCW = forms.FloatField()

class Covercallbt(forms.Form):
    startdateBt = forms.DateField()
    enddateBt = forms.DateField()
    timerange = forms.FloatField()
    c = forms.FloatField()
    m = forms.FloatField()
    n = forms.FloatField()

class Backtestcover(forms.Form):
    enddateBt = forms.DateField()
    timerange = forms.FloatField()
    rate = forms.FloatField()
    strikePrice = forms.FloatField()
    symbol = forms.CharField()
    maturity = forms.FloatField()

class Backtester(forms.Form):
    enddateBt = forms.DateField()
    timerange = forms.FloatField()
    m = forms.FloatField()
    n = forms.FloatField()
    symbol = forms.CharField()

covercall/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import Covercallstrate
from .models import CoverCallStrate
from .forms import Closeprice
from .models import ClosePrice
from .forms import Cwprice, Covercallbt, Backtestcover, Backtester
from .models import CWPrice, CoverCallBacktest, BackTestCover, BackTester
import numpy as np
import scipy.stats as si
import sympy as sy
from sympy.stats import Normal, cdf
from sympy import init_printing
import pandas as pd
from datetime import datetime, timedelta
import math
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from io import BytesIO
import base64
import statistics
import time
init_printing()
# Create your views here.

def call_option_price(S, K, t, r, sigma):
    d1 = [np.log(S / K) + (r + ((sigma**2) / 2)) * t] / (sigma * np.sqrt(t))
    d2 = d1 - sigma * np.sqrt(t)
    call_price = S * si.norm.cdf(d1, 0.0, 1.0) - K * np.exp(-r * t) *  si.norm.cdf(d2, 0.0, 1.0)
    return call_price, si.norm.cdf(d1, 0.0, 1.0)[0]

def put_option_price(S, K, t, r, sigma):
    d1 = [np.log(S / K) + (r + ((sigma**2) / 2)) * t] / (sigma * np.sqrt(t))
    d2 = d1 - sigma * np.sqrt(t)
    put_price = K * np.exp(-r * t)*si.norm.cdf(-d2, 0.0, 1.0) - S * si.norm.cdf(-d1, 0.0, 1.0)
    return put_price

def save_covercall(request):
    if request.method == "POST":
        data = Covercallstrate(request.POST)
        if data.is_valid():
            startDate = data.cleaned_data['startDate']
            endDate = data.cleaned_data['endDate']
            symbol = data.cleaned_data['symbol']
            covercall = CoverCallStrate(assetPrice = data.cleaned_data['assetPrice'],
                strikePrice = data.cleaned_data['strikePrice'],
                maturity = data.cleaned_data['maturity'],
                rate = data.cleaned_data['rate'],
                startDate = data.cleaned_data['startDate'],
                endDate = data.cleaned_data['endDate'],
                symbol = data.cleaned_data['symbol'])
            covercall.save()
            volatility = get_volatility(startDate, endDate, symbol)
            call, deltaOptions = call_option_price(data.cleaned_data['assetPrice'], data.cleaned_data['strikePrice'],
                data.cleaned_data['maturity'], data.cleaned_data['rate'], volatility)
            put = put_option_price(data.cleaned_data['assetPrice'], data.cleaned_data['strikePrice'],
                data.cleaned_data['maturity'], data.cleaned_data['rate'], volatility)
            tradeDate = get_date(startDate, endDate, symbol)
            prices = get_price(startDate, endDate, symbol)
            prices = prices.to_numpy()
            plt.plot(tradeDate, prices, color='green', label='prices')
            plt.title('Prices figures:')
            plt.xlabel('Timestamp')
            plt.ylabel('Prices')
            buffer = BytesIO()
            plt.savefig(buffer, format='png')
            buffer.seek(0)
            image_png = buffer.getvalue()
            buffer.close()
            graphic = base64.b64encode(image_png)
            graphic = graphic.decode('utf-8')
            fdateCW = CWPrice.objects.values('dateCW').first()
            fdateCW = list(fdateCW.values())[0].strftime("%d-%m-%Y")
            ldateCW = CWPrice.objects.values('dateCW').last()
            ldateCW = list(ldateCW.values())[0].strftime("%d-%m-%Y")
            return render(request, 'covercall/campaign.html', {'assetPrice': data.cleaned_data['assetPrice'], 
                'strikePrice':  data.cleaned_data['strikePrice'], 'graphic': graphic, 'fdateCW': fdateCW, 
                'ldateCW': ldateCW, 'call': call[0], 'deltaOptions': deltaOptions, 'volatility': volatility, 'put': put[0],
                'rate': data.cleaned_data['rate'], 'symbol': symbol})
        else:
            return HttpResponse('Bad Request')

def show_symbol(request):
    symbols = ClosePrice.objects.values('symbol').distinct()
    return render(request, 'covercall/symbol.html', {'symbols': symbols})

def get_date(startDate, endDate, symbol):
    tradeDate = ClosePrice.objects.filter(symbol = symbol).values('date')
    tradeDate = tradeDate.filter(date__gte = startDate, date__lte = endDate)
    tradeDate = list(tradeDate)
    list_date = []
    for index, date in enumerate(tradeDate):
        list_date.append(tradeDate[index]['date'])
    for index, date in enumerate(list_date):
        list_date[index] = datetime.strftime(list_date[index], "%d-%m-%Y") 
    return np.array(list_date)

def get_price(startDate, endDate, symbol):
    closeprice =  ClosePrice.objects.filter(symbol = symbol).values('closePrice')
    closeprice = closeprice.filter(date__gte = startDate, date__lte = endDate)
    arr_price = np.zeros(len(closeprice), )
    for index, price in enumerate(closeprice):
        arr_price[index] = price['closePrice']
    s_price = pd.Series(arr_price)
    return s_price

def calculate_volatility(data):
    logPrice = np.log(data / data.shift(1))
    daily_std =  np.std(logPrice)
    return daily_std * 252 ** 0.5

def get_volatility(startDate, endDate, symbol):
    volatility = calculate_volatility(get_price(startDate, endDate, symbol))
    return volatility 

def index(request, symbol):
    covercall = Covercallstrate
    return render(request, 'covercall/index.html', {'covercall': covercall, 'symbol': symbol})

# def backtest(request):
#     if request.method == "POST":
#         data = Covercallbt(request.POST)
#         #return render(request, 'covercall/backtest.html', {'data': data})
#         if data.is_valid():
#             startdateBt = data.cleaned_data['startdateBt']
#             enddateBt = data.cleaned_data['enddateBt']
#             timerange = data.cleaned_data['timerange'] / 2
#             c = data.cleaned_data['c']
#             m = data.cleaned_data['m']
#             n = data.cleaned_data['n']
#             covercallbacktest = CoverCallBacktest(startdateBt = data.cleaned_data['startdateBt'],
#                 enddateBt = data.cleaned_data['enddateBt'],
#                 timerange = data.cleaned_data['timerange'] / 2,
#                 c = data.cleaned_data['c'],
#                 m = data.cleaned_data['m'],
#                 n = data.cleaned_data['n'])
#             covercallbacktest.save()
#             listV, listDate, CWdate = portfolio_value(startdateBt, enddateBt, c, m, n)
#             listReturns = getReturns(listV)
#             listday = []
#             for i in range(0, 14):
#                 listday.append(i)
#             listReturnsrange, listTimerange = range_returns(startdateBt, enddateBt, int(timerange), c, m, n)
#             avgreturn = []
#             for r in listReturnsrange:
#                 avgreturn.append(sum(r)/len(r))
#             log_avg_return = getReturns(avgreturn)
#             plt.plot(listday, log_avg_return, color='green', label='prices')
#             plt.title('Log returns average graph:')
#             plt.xlabel('Date')
#             plt.ylabel('Log Returns average')
#             buffer = BytesIO()
#             plt.savefig(buffer, format='png')
#             buffer.seek(0)
#             image_png = buffer.getvalue()
#             buffer.close()
#             imageReturn = base64.b64encode(image_png)
#             imageReturn = imageReturn.decode('utf-8')
#             return render(request, 'covercall/backtest.html', {'c': data.cleaned_data['c'],
#                 'startDate': data.cleaned_data['startdateBt'], 'endDate': data.cleaned_data['enddateBt'],
#                 'timerange': data.cleaned_data['timerange'] / 2, 'listV': listV, 'listReturns': listReturns,
#                 'listReturnsrange': listReturnsrange, 'imageReturn': imageReturn, 'avgreturn': avgreturn , 'log_avg_return': log_avg_return})
#         else:   
#             return HttpResponse('Bad Request')

def getV(c, m, n, s):
    return n*s - m*c

# def portfolio_value(startDate, endDate, c, m , n):
#     tradeDate = CWPrice.objects.filter(dateCW__gte = startDate, dateCW__lte = endDate).values('dateCW')
#     tradeDate = list(tradeDate.values())
#     CWdate = []
#     for date in tradeDate:
#         CWdate.append(date['dateCW'].strftime("%Y-%m-%d"))
#     listDate = []
#     for date in tradeDate:
#         listDate.append(date['dateCW'].strftime("%m-%d"))
#     listV = []
#     for index, date in enumerate(CWdate):
#         s = CWPrice.objects.filter(dateCW = date).values('closePriceCW')
#         listV.append(getV(c, m, n, s[0]['closePriceCW']))
#     return np.array(listV), np.array(listDate), np.array(CWdate)

def getReturns(val):
    logReturns = []
    for i, v in enumerate(val):
        logReturns.append(val[i]/val[0])
    return np.array(logReturns)

def range_returns(startDate, endDate, timerange, c, m, n):
    idStart = CWPrice.objects.filter(dateCW=startDate).values('id')
    idStart = int(idStart[0]['id'])
    idEnd = CWPrice.objects.filter(dateCW=endDate).values('id')
    idEnd = int(idEnd[0]['id'])
    listReturns = []
    listV = []
    listtimerange = []
    listDate = []
    for i in range(idStart, int((idEnd-idStart))):
        timetrade = CWPrice.objects.values('dateCW')[i-1:timerange]
        listtimerange.append(timetrade)
        CWdate = []
        for date in timetrade:
            CWdate.append(date['dateCW'].strftime("%Y-%m-%d"))
        for index, date in enumerate(CWdate):
            s = CWPrice.objects.filter(dateCW = date).values('closePriceCW')
            listV.append(getV(c, m, n, s[0]['closePriceCW']))
        listReturns.append(getReturns(listV))
    return np.array(listReturns), np.array(listtimerange)
    
def estimate(request):
    if request.method == "POST":
        data = Backtestcover(request.POST)
        #return render(request, 'covercall/backtest.html', {'data': data})
        if data.is_valid():
            enddateBt = data.cleaned_data['enddateBt']
            #return render(request, 'covercall/backtest.html', {'enddateBt': enddateBt})

covercall/templates/covercall/backtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'covercall/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Estimate Backtest</h2>
        {% comment %} {{enddateBt}} {% endcomment %}
        <form action="{% url 'appcovercall:backtestting' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-3">
                    {% comment %} <div class="form-group">
                        <label for="To">To:</label></br>
                        <input type="text" name="enddateBt" id="" value="{{enddateBt}}" readonly>
                    </div> {% endcomment %}
                    <div class="form-group">
                            <label for="Timerange">Time range(days):</label></br>
                            <input type="number" name="timerange" id="" readonly value="{{timerange}}">
                        </div>
                    <div class="form-group">
                        <label for="strikePrice">Strike Price:</label></br>
                        <input type="text" id="strikePrice" value="{{strikePrice}}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="assetPrice">Asset Price:</label></br>
                        <input type="text" id="C" value="{{assetPrice}}" name="assetPrice">
                    </div>  
                    <div class="form-group">
                        <label for="vol">Volatility:</label></br>
                        <input type="text" id="volatility" value="{{volatility}}" name="volatility">
                    </div>
                    <div class="form-group">
                        <label for="To">To:</label></br>
                        <input type="text" name="enddateBt" id="enddateBt" value="{{enddateBt}}">
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        <label for="vol">Symbol:</label></br>
                        <input type="text" id="symbol" value="{{symbol}}" name="symbol">
                    </div>
                    <div class="form-group">
                        <label for="vol">Hedge ratio:</label></br>
                        <input type="text" id="delta" value="{{hed}}" name="hedge ratio">
                    </div>  
                    <div class="form-group">
                        <label for="vol">Number of Options:</label></br>
                        <input type="text" id="m" name="m">
                    </div>
                    <div class="form-group">
                        <label for="vol">Number of Stocks:</label></br>
                        <input type="text" id="n" name="n">
                    </div>
                    
                    <button type="button" class="btn bg-success text-white" onclick="processcampain()">Estimate</button>
                    <button type="submit" class="btn bg-success text-white">Test</button>    
                </div>
                {% comment %} <div class="col-3">
                    <div class="form-group">
                        <button type="button" class="btn bg-success text-white" onclick="processcampain()">Estimate</button>
                    </div>   
                </div> {% endcomment %}
            </div>
            {% comment %} <button type="button" class="btn bg-success text-white" onclick="processcampain()">Estimate</button>
            <button type="submit" class="btn bg-success text-white">Test</button> {% endcomment %}
        </form>
        {% comment %} <img src="data:image/png;base64,{{ imageReturn|safe }}"> {% endcomment %}
      </div>
</body>
<script>
    function processcampain(){
        document.getElementById("n").value = document.getElementById("m").value * document.getElementById("delta").value 
    }
</script>
</html>

covercall/templates/covercall/campaign.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'covercall/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Cover Call Campaign</h2>
        <h3>Black-Scholes Table</h3>
        {{matu}}
        {{data}}
        <div class="row">
            <div class="col">
                <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">Label</th>
                        <th scope="col">Value</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Stock Asset Price:</th>
                            <th scope="col"><input type="text" class="form-control" id="S" value="{{ assetPrice }}" readonly></th>
                        </tr>
                        <tr>
                            <th scope="row">Option Strike Price:</th>
                            <th scope="col"><input type="text" class="form-control" id="St" value="{{ strikePrice }}" readonly></th>
                        </tr>
                        <tr>
                            <th scope="row">Volatility:</th>
                            <th scope="col"><input type="text" class="form-control" id="vol" value="{{ volatility }}" readonly></th>
                        </tr>
                        <tr>
                            <th scope="row">European Call:</th>
                            <th scope="col"><input type="text" class="form-control" id="C" value="{{ call }}" readonly></th>
                        </tr>
                        <tr>
                            <th scope="row">European Put:</th>
                            <th scope="col"><input type="text" class="form-control" id="P" value="{{ put }}" readonly></th>
                        </tr>
                    </tbody>
                  </table>
            </div>
            <img src="data:image/png;base64,{{ graphic|safe }}">
            {% comment %} <h4>Backtester from {{fdateCW}} to {{ldateCW}}</h4> {% endcomment %}
            {% comment %} <form action="{% url 'appcovercall:backtestting' %}" method="POST"> {% endcomment %}
            <form action="{% url 'appcovercall:backtestdemo' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm">
                        <div class="form-group">
                            <label for="maturity">Maturity:</label></br>
                            <input type="text" name="maturity" id="maturity">
                            <small id="ex1" class="form-text text-muted">Example: "0.5"</small>
                        </div>
                        <div class="form-group">
                            <label for="strikeprice">Strike Price:</label></br>
                            <input type="text" name="strikePrice" id="strikePrice">
                            <small id="ex1" class="form-text text-muted">Example: "158"</small>
                        </div> 
                        <div class="form-group">
                            <label for="assetprice">Stock Symbol:</label></br>
                            <input type="text" name="symbol" id="" value="{{symbol}}" readonly>
                        </div>  
                        <div class="form-group">
                            <label for="rate">Rate:</label></br>
                            <input type="text" name="rate" id="rate" value={{rate}}>
                            <small id="ex1" class="form-text text-muted">Example: "0.05"</small>
                        </div>
                        <div class="form-group">
                            <label for="assetprice">End:</label></br>
                            <input type="date" name="enddateBt" id="endDate" >
                            <small id="ex1" class="form-text text-muted">Example: "01-08-2019"</small>
                        </div>
                        <div class="form-group">
                            <label for="assetprice">Time range:</label></br>
                            <input type="text" name="timerange" id="timerange">
                            <small id="ex1" class="form-text text-muted">Example: "5"</small>
                        </div>
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Test</button>
                        </div>   
                    </div>
                </div>
                {% comment %} <button type="submit" class="btn btn-primary">Test</button> {% endcomment %}
            </form>
        </div>
    </div>
      {% comment %} <script>
          function processcampain(){
            document.getElementById("N").value = document.getElementById("M").value * document.getElementById("delta").value
            var startDate = new Date(document.getElementById('startDate').value);
            var endDate = new Date(document.getElementById('endDate').value);
            deltaTime = Math.abs(endDate - startDate);
            document.getElementById('timerange').value = deltaTime/(24*1000*60*60) 
          }
      </script> {% endcomment %}
</body>
</html>

covercall/templates/covercall/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'covercall/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Options Calculator</h2>
        <form action="{% url 'appcovercall:saveCoverCall' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        <label for="assetprice">Stock Symbol:</label></br>
                        <input type="text" name="symbol" id="" value="{{symbol}}" readonly>
                        <small id="ex1" class="form-text text-muted">Example: "FPT"</small>
                    </div>    

                    <div class="form-group">
                        <label for="assetprice">Stock Asset Price:</label></br>
                        {{ covercall.assetPrice }}
                        <small id="ex1" class="form-text text-muted">Example: "25.00"</small>
                    </div>

                    <div class="form-group">
                        <label for="strikeprice">Option Strike Price:</label></br>
                        {{ covercall.strikePrice }}
                        <small id="ex1" class="form-text text-muted">Example: "15.00"</small>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="maturity">Start Date:</label></br>
                        <input type="date" name="startDate" id="startDate">
                        <small id="ex1" class="form-text text-muted">Example: "23-04-2020"</small>
                    </div>

                    <div class="form-group">
                        <label for="maturity">End Date:</label></br>
                        <input type="date" name="endDate" id="endDate">
                        <small id="ex1" class="form-text text-muted">Example: "01-04-2021"</small>
                    </div>

                    <div class="form-group">
                        <label for="maturity">Expiration Date:</label></br>
                        <input type="date" name="expirationDate" id="expirationDate" oninput="time_to_expi()" >
                        <small id="ex1" class="form-text text-muted">Example: "01-07-2021"</small>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        <label for="maturity">Maturity (Time Until Expiration):</label></br>
                        <input type="text" name="maturity" id="maturity" >
                        <small id="ex1" class="form-text text-muted">Example: "3.5"</small>
                    </div>

                    <div class="form-group">
                        <label for="rate">Risk-Free Interest Rate:</label></br>
                        <!-- <input type="password" class="form-control" id="exampleInputPassword1"> -->
                        {{ covercall.rate }}
                        <small id="ex1" class="form-text text-muted">Example: "0.05" (for 5%)"</small>
                    </div>

                    <div class="form-group">
                        <label for="volatility">Black-Scholes:</label></br>
                        <!-- <input type="number" name="volatility" id="volatility">
                        <small id="ex1" class="form-text text-muted">Example: "0.20" (for 20%)</small> -->
                        <button type="submit" class="btn bg-success text-white">Calculate</button>
                    </div>
                </div>
            </div>
            <!-- <div class="row">
                <div class="col-sm"></div>
                <div class="col-sm">
                    <button type="submit" class="btn bg-success text-white">Submit</button>
                </div>
                <div class="col-sm"></div>
            </div>     -->
        </form>
      </div>
</body>
<script>
    function time_to_expi(){
        // var startDate = document.getElementById('startDate').value;
        // var exprirationDate = document.getElementById('expirationDate').value;
        var startDate = new Date(document.getElementById('startDate').value);
        var expDate = new Date(document.getElementById('expirationDate').value);
        deltaTime = Math.abs(expDate - startDate);
        document.getElementById('maturity').value = parseFloat(Math.ceil((deltaTime / (1000 * 60 * 60 * 24))) / 365); 
    }
</script>
</html>

covercall/templates/covercall/symbol.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'covercall/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>List Company's Symbols</h2>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Symbols</th>
                <th scope="col">Black-Scholes</th>
                </tr>
            </thead>
            <tbody>
                {% for s in symbols  %}
                <tr>
                <td> {{ s.symbol }} </td>
                <td> <a href="{% url 'appcovercall:home' s.symbol %}">Calculate Options of {{s.symbol}}</a> </td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
      </div>
</body>
</html>