covercall/urls.py
from django.urls import path, include
from . import views
app_name = 'appcovercall'
urlpatterns = [
    path('home/<str:symbol>', views.index, name='home'),
    path('saveCoverCall/', views.save_covercall, name='saveCoverCall'),
    path('showSymbol/', views.show_symbol, name='showSymbol'),
    path('backtestting/', views.backtest, name='backtestting'),
    path('backtestdemo/', views.estimate, name='backtestdemo')
]

covercallbacktest/urls.py
from django.urls import path, include
from . import views
app_name = 'appcovercallbacktest'
urlpatterns = [
    path('backtesting/', views.index, name='backtesting'),
    path('backtesting_covercall/', views.backtesting_covercall, name='backtesting_covercall'),
]

coverwarranty/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('covercall/', include('covercall.urls')),
    path('covercall_backtest/', include('covercallbacktest.urls')),
    path('fpt2003backtest/', include('fpt2003backtest.urls')),
]

covercallbacktest/models.py
from django.db import models
from django.db.models import Model
# Create your models here.
class CoverCallBacktest(models.Model):
    symbol = models.CharField(max_length=10)
    startDate = models.DateField()
    endDate = models.DateField()
    callPrice = models.FloatField(null=True)
    strikePrice = models.FloatField(null=True)

covercallbacktest/forms.py
from django import forms

class Covercallbacktest(forms.Form):
    symbol = forms.CharField()
    startDate = forms.DateField(input_formats=["%d-%m-%Y"])
    endDate = forms.DateField(input_formats=["%d-%m-%Y"])
    callPrice = forms.FloatField()
    strikePrice = forms.FloatField()

covercallbacktest/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import Covercallbacktest
from .models import CoverCallBacktest
from covercall.models import ClosePrice
import numpy as np
import pandas as pd
import math
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from io import BytesIO
import base64
import statistics
import time
def index(request):
    backtest = Covercallbacktest 
    # closeprice =  ClosePrice.objects.filter(symbol = 'FPT').values('closePrice')
    # closeprice = closeprice.filter(date__gte = "2014-01-15", date__lte = "2014-01-20")
    # arr_price = np.zeros(len(closeprice), )
    # for index, price in enumerate(closeprice):
    #     arr_price[index] = price['closePrice']
    # s_price = pd.Series(arr_price)
    # volatility = calculate_volatility(s_price)
    return render(request, 'covercallbacktest/index.html', {'backtest': backtest})

def calculate_volatility(data):
    logPrice = np.log(data / data.shift(1))
    daily_std = np.std(logPrice)
    return daily_std.item() * 252 ** 0.5

def get_price(startDate, endDate, symbol):
    closeprice =  ClosePrice.objects.filter(symbol = symbol).values('closePrice')
    closeprice = closeprice.filter(date__gte = startDate, date__lte = endDate)
    arr_price = np.zeros(len(closeprice), )
    for index, price in enumerate(closeprice):
        arr_price[index] = price['closePrice']
    s_price = pd.Series(arr_price)
    return s_price

def get_date(startDate, endDate, symbol):
    tradeDate = ClosePrice.objects.filter(symbol = symbol).values('date')
    tradeDate = tradeDate.filter(date__gte = startDate, date__lte = endDate)
    tradeDate = list(tradeDate)
    list_date = []
    for index, date in enumerate(tradeDate):
        list_date.append(tradeDate[index]['date'])
    for index, date in enumerate(list_date):
        list_date[index] = datetime.strftime(list_date[index], "%d-%m-%Y") 
    return np.array(list_date)

def get_volatility(startDate, endDate, symbol):
    volatility = calculate_volatility(get_price(startDate, endDate, symbol))
    return volatility

def get_mean(startDate, endDate, symbol):
    return statistics.mean(get_price(startDate, endDate, symbol))

def get_max_min_price(startDate, endDate, symbol):
    closeprice =  ClosePrice.objects.filter(symbol = symbol).values('closePrice')
    closeorice = closeprice.filter(date__gte = startDate, date__lte = endDate)
    arr_price = np.zeros(len(closeprice), )
    for index, price in enumerate(closeprice):
        arr_price[index] = price['closePrice']
    return np.amax(arr_price), np.amin(arr_price)

def get_log_returns(startDate, endDate, symbol):
    s_price = get_price(startDate, endDate, symbol)
    return (np.log(s_price) - np.log(s_price.shift(1))).tolist()

def profit_loss(assetprice, breakevenPoint):
    if assetprice != breakevenPoint:
        return assetprice - breakevenPoint
    else:
        return 0

def portfolio_value(startDate, endDate, symbol, breakevenPoint):
    s_price = get_price(startDate, endDate, symbol)
    portfolio = np.zeros(len(s_price), )
    for index, price in enumerate(s_price):
        portfolio[index] = profit_loss(price, breakevenPoint)
    profit = np.zeros(len(portfolio), )
    loss = np.zeros(len(portfolio), )
    for i, price in enumerate(portfolio):
        if price > 0:
            profit[i] = price
        elif price < 0:
            loss[i] = price    
    return profit, loss

def backtesting_covercall(request):
    if request.method == "POST":
        data = Covercallbacktest(request.POST)
        #return render(request, 'covercallbacktest/backtest.html', {'data': data})
        if data.is_valid():
            symbol = data.cleaned_data['symbol']
            startDate = data.cleaned_data['startDate']
            endDate = data.cleaned_data['endDate']
            callPrice = data.cleaned_data['callPrice']
            strikePrice = data.cleaned_data['strikePrice']
            strategy_backtester = CoverCallBacktest(symbol = data.cleaned_data['symbol'], 
                startDate = data.cleaned_data['startDate'], 
                endDate = data.cleaned_data['endDate'], 
                callPrice = data.cleaned_data['callPrice'], 
                strikePrice = data.cleaned_data['strikePrice'])
            volatility = get_volatility(startDate, endDate, symbol)
            breakevenPoint = callPrice + strikePrice
            # sDate = datetime.strptime(startDate, "%d-%m-%Y")
            # eDate = datetime.strptime(endDate, "%d-%m-%Y")
            deltaTime = endDate - startDate
            maxPrice, minPrice = get_max_min_price(startDate, endDate, symbol)
            profit, loss = portfolio_value(startDate, endDate, symbol, breakevenPoint)
            maxProfit = np.amax(profit)
            maxLoss = np.amax(loss)
            if maxLoss < 0:
                maxLoss = maxLoss * -1
            minProfit = np.amin(profit)
            minLoss = np.amin(loss)
            if minLoss < 0:
                minLoss = minLoss * -1
            mean = get_mean(startDate, endDate, symbol)
            logReturn = get_log_returns(startDate, endDate, symbol)
            logReturn = [x for x in logReturn if math.isnan(x) == False]
            tradeDate = get_date(startDate, endDate, symbol)
            for index, date in enumerate(tradeDate):
                tradeDate[index] = time.mktime(datetime.strptime(tradeDate[index], "%d-%m-%Y").timetuple())
            prices = get_price(startDate, endDate, symbol)
            prices = prices.to_numpy()
            plt.plot(tradeDate, prices, color='green', label='prices')
            plt.title('Prices figures:')
            plt.xlabel('Timestamp')
            plt.ylabel('Prices')
            buffer = BytesIO()
            plt.savefig(buffer, format='png')
            buffer.seek(0)
            image_png = buffer.getvalue()
            buffer.close()
            graphic = base64.b64encode(image_png)
            graphic = graphic.decode('utf-8')
            strategy_backtester.save()
            #return render(request, 'covercallbacktest/backtest.html', {'tradeDate': tradeDate})
            return render(request, 'covercallbacktest/backtest.html', {'breakevenPoint': breakevenPoint, 'startDate': startDate, 'endDate': endDate,
                'deltaTime': deltaTime, 'volatility': volatility, 'maxPrice': maxPrice, 'minPrice': minPrice, 'mean': mean, 'logReturn': max(logReturn),
                'maxProfit': maxProfit, 'minProfit': minProfit,'maxLoss': maxLoss, 'minLoss': minLoss, 'symbol': symbol, 'tradeDate': tradeDate, 'graphic': graphic})
        else:
            return HttpResponse('Bad Request')

covercallbacktest/templates/covercallbacktest/backtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'covercall/style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Covered Call Backtester of {{ symbol }}</h2>
        <form action="" method="">
            {% csrf_token %}
            <div class="form-group">
                <label for="assetprice">Breakeven Point:</label></br>
                <input type="text" class="form-control" id="breakevenPoint" value="{{ breakevenPoint }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Mean:</label></br>
                <input type="text" class="form-control" id="mean" value="{{ mean }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Volatility:</label></br>
                <input type="text" class="form-control" id="volatility" value="{{ volatility }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Start Date:</label></br>
                <input type="text" class="form-control" id="startDate" value="{{ startDate }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">End Date:</label></br>
                <input type="text" class="form-control" id="endDate" value="{{ endDate }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Delta time:</label></br>
                <input type="text" class="form-control" id="deltaTime" value="{{ deltaTime }}" readonly>
            </div>

            <img src="data:image/png;base64,{{ graphic|safe }}">


            <div class="form-group">
                <label for="assetprice">Max Price:</label></br>
                <input type="text" class="form-control" id="maxPrice" value="{{ maxPrice }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Min Price:</label></br>
                <input type="text" class="form-control" id="minPrice" value="{{ minPrice }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Max Logarit Returns:</label></br>
                <input type="text" class="form-control" id="logReturn" value="{{ logReturn }}" readonly>
            </div>
            
            <div class="form-group">
                <label for="assetprice">Max Profit: </label></br>
                <input type="text" class="form-control" id="maxProfit" value="{{ maxProfit }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Min Profit:</label></br>
                <input type="text" class="form-control" id="minProfit" value="{{ minProfit }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Max Loss: </label></br>
                <input type="text" class="form-control" id="maxLoss" value="{{ maxLoss }}" readonly>
            </div>

            <div class="form-group">
                <label for="assetprice">Min Loss:</label></br>
                <input type="text" class="form-control" id="minLoss" value="{{ minLoss }}" readonly>
            </div>
        </form>
      </div>
</body>
</html>

covercallbacktest/templates/covercallbacktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cover Warranty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <h2>Covered Call Backtesting</h2>
        <!-- {{backtest}} -->
        <form action="{% url 'appcovercallbacktest:backtesting_covercall' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="assetprice">Symbol Shares:</label></br>
                {{ backtest.symbol }}
                <small id="ex1" class="form-text text-muted">Example: "FPT"</small>
            </div>

            <div class="form-group">
                <label for="assetprice">Start Date:</label></br>
                {{ backtest.startDate }}
                <small id="ex1" class="form-text text-muted">Example: "27-01-2014"</small>
            </div>

            <div class="form-group">
                <label for="assetprice">End Date:</label></br>
                {{ backtest.endDate }}
                <small id="ex1" class="form-text text-muted">Example: "01-07-2021"</small>
            </div>

            <div class="form-group">
                <label for="assetprice">Call Prices:</label></br>
                {{ backtest.callPrice }}
                <small id="ex1" class="form-text text-muted">Example: "26600"</small>
            </div>

            <div class="form-group">
                <label for="assetprice">Strike Prices:</label></br>
                {{ backtest.strikePrice }}
                <small id="ex1" class="form-text text-muted">Example: "30000"</small>
            </div>

          <button type="submit" class="btn bg-success text-white">Submit</button>
        </form>
      </div>
</body>
</html>